---
name: Get Instance Types test

# Trigger this workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Job to get a full list of instance types in JSON format
  test-1:
    name: Full list json
    runs-on: ubuntu-latest  # Run this job on the latest Ubuntu runner
    steps:
      - name: Call get-instance-types action
        id: get-instance-types
        uses: iferaorg/lambdalabs-get-instance-types-action@main  # Use custom action to get instance types
        with:
          available_only: false  # Fetch all instance types, including unavailable ones
          names_only: false  # Fetch full details in JSON format
        env:
          LAMBDA_TOKEN: ${{ secrets.LAMBDA_TOKEN }}  # Use secret token for authentication
      - name: Check outputs
        run: |
            echo "${{ steps.get-instance-types.outputs.instance_types }}"  # Print the output of the custom action

  # Job to get a list of available instance types in JSON format
  test-2:
    name: Available only json
    runs-on: ubuntu-latest
    steps:
      - name: Call get-instance-types action
        id: get-instance-types
        uses: iferaorg/lambdalabs-get-instance-types-action@main
        with:
          available_only: true  # Fetch only available instance types
          names_only: false
        env:
          LAMBDA_TOKEN: ${{ secrets.LAMBDA_TOKEN }}
      - name: Check outputs
        run: |
            echo "${{ steps.get-instance-types.outputs.instance_types }}"

  # Job to get a full list of instance type names only
  test-3:
    name: Full list names only
    runs-on: ubuntu-latest
    steps:
      - name: Call get-instance-types action
        id: get-instance-types
        uses: iferaorg/lambdalabs-get-instance-types-action@main
        with:
          available_only: false
          names_only: true  # Fetch only the names of the instance types
        env:
          LAMBDA_TOKEN: ${{ secrets.LAMBDA_TOKEN }}
      - name: Check outputs
        run: |
              echo "${{ steps.get-instance-types.outputs.instance_types }}"

  # Job to get a list of available instance type names only
  test-4:
    name: Available names only
    runs-on: ubuntu-latest
    steps:
      - name: Call get-instance-types action
        id: get-instance-types
        uses: iferaorg/lambdalabs-get-instance-types-action@main
        with:
          available_only: true  # Fetch only available instance types
          names_only: true  # Fetch only the names of the instance types
        env:
          LAMBDA_TOKEN: ${{ secrets.LAMBDA_TOKEN }}
      - name: Check outputs
        run: |
            echo "${{ steps.get-instance-types.outputs.instance_types }}"