---
name: Launch / Terminate Test

# Trigger this workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Job to get a full list of instance types in JSON format
  test-1:
    name: Launch instance
    runs-on: ubuntu-latest # Run this job on the latest Ubuntu runner
    outputs:
      instance_id: ${{ steps.launch-instance.outputs.instance_id }}
    steps:
      - name: Call launch action
        id: launch-instance
        uses: iferaorg/lambdalabs-launch-action@main # Use custom action to launch instance
        with:
          instance_type_name: "gpu_1x_a10" # Launch a GPU instance
          region_name: "us-west-1" # Launch in the US West 1 region
          ssh_key_names: "lambda_ssh_001"
          lambda_token: ${{ secrets.LAMBDA_TOKEN }} # Use secret token for authentication
          wait_for_boot: "true" # Wait for the instance to boot
          boot_timeout: "600" # Set the boot timeout to 10 minutes
      - name: Check outputs
        run: |
          echo '${{ steps.launch-instance.outputs.instance_id }}'

  test-2:
    if: ${{ always() }}
    needs: test-1
    name: Terminate instance
    runs-on: ubuntu-latest
    steps:
      - name: Call terminate action
        id: terminate-instance
        uses: iferaorg/lambdalabs-terminate-action@main
        with:
          instance_id: ${{ needs.test-1.outputs.instance_id }}
          lambda_token: ${{ secrets.LAMBDA_TOKEN }}
          wait_for_termination: "true"
          termination_timeout: "600"